version: "3"
services:
  db:
    image: mongo:4.0
    container_name: mtv_db
    ports:
      - "127.0.0.1:27018:27017"
    command: bash -c "mongod --bind_ip_all --port 27017 --logpath /mtv/log/db.log --fork && tail -F anything"
    volumes:
      - ./db-instance/data:/mtv/data
      - ./db-instance/log:/mtv/log
      - ./db-instance/dump:/mtv/dump
  app:
    build: .
    container_name: mtv_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: mtv run --env production -v --docker

  client:
    build: client
    container_name: mtv_client
    depends_on: 
      - app
    ports: 
      - 4200:4200
      - 80:4200
    command: serve -s /client/build -p 4200
